# fly.toml app configuration file generated for powerslamverse on 2023-11-30T11:46:23-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "powerslamverse"
primary_region = "yyz"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
[deploy]
  release_command = "./bin/rails db:prepare"

